### ISSUE TITLE
Add screenshot and link to GitHub to Firefox addons page

### ISSUE THREAD

**Issue by Nekzuris** [cmoffroad/id-strava-heatmap-extension#4]
The Firefox addons page feels empty
https://addons.mozilla.org/en-US/firefox/addon/id-strava-heatmap/

Link to here should also be added to the Chrome addons pages
https://chromewebstore.google.com/detail/id-strava-heatmap/eglbcifjafncknmpmnelckombmgddlco

**Comment by cmoffroad** [comment]
Done, thanks for reporting it.

The link in the Chrome extension page will be updated once approved by Google.

**Comment by Nekzuris** [comment]
I wanted to close this but I still don't see the link to GitHub on Chrome despite the update yesterday.
Also the link on Firefox being labeled "Homepage" instead of "GitHub" makes it hard to find, not sure if you can change that.

**Comment by cmoffroad** [comment]
> I wanted to close this but I still don't see the link to GitHub on Chrome despite the update yesterday.

I have added now the link to Github on both Firefox and Chrome add-on description.

> Also the link on Firefox being labeled "Homepage" instead of "GitHub" makes it hard to find, not sure if you can change that.

I have added a "Support Site" link that redirects to Github.
